version: "3.8"

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:3000"
    depends_on:
      - auth-service
      - job-service
      - ai-analysis-service
      - data-cleaning-service

  auth-service:
    build: ./auth-service
    ports:
      - "8081:3000"
    depends_on:
      - db

  job-service:
    build: ./job-service
    ports:
      - "8082:3000"
    depends_on:
      - db

  payment-service:
    build: ./payment-service
    ports:
      - "8083:3000"
    depends_on:
      - db

  scraping-service:
    build: ./scraping-service
    ports:
      - "8084:3000"
    depends_on:
      - db

  user-service:
    build: ./user-service
    ports:
      - "8085:3000"
    depends_on:
      - db

  ai-analysis-service:
    build: ./ai-analysis-service
    ports:
      - "8090:8000"
    depends_on:
      - db

  data-cleaning-service:
    build: ./data-cleaning-service
    ports:
      - "8091:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: scrapesmith
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
