version: "3.8"
services:
  auth-service:
    image: auth-service
    container_name: auth-service
    env_file:
      - .env  # Load environment variables from .env file
    ports:
      - "3000:3000"
    networks:
      - kong-net

  kong:
    image: kong:3.4
    container_name: kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/usr/local/kong/declarative/kong.yml"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./kong/kong.yml:/usr/local/kong/declarative/kong.yml:ro
    depends_on:
      - auth-service
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge
